version: '2'
services:
  app:
    build: .
    links:
      - db
    ports:
      - 5016:5016

  db:
    image: mysql:5.7
    ports:
      - 32000:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
